version: "3"
volumes:
  mysql_8_0-data:
  vendor_bundle_2_5_1:

services:
  mysql:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: password
    networks:
      - default
    ports:
      - '33306:3306'
    volumes:
      - mysql_8_0-data:/var/lib/mysql
  web:
    build:
      context: .
      dockerfile: Dockerfile.dev
    ports:
      - '3000:3000'
    environment:
      MYSQL_USERNAME: root
      MYSQL_PASSWORD: password
      MYSQL_HOST: mysql
    depends_on:
      - mysql
    networks:
      - default
    volumes:
      - .:/web
      # https://qiita.com/shotat/items/57d049793605ffc20135
      - /web/log
      - /web/tmp
      # - /web/vendor/bundle
      - vendor_bundle_2_5_1:/web/vendor/bundle
    tty: true
    stdin_open: true
    command: bundle exec rails server -b 0.0.0.0
